name: Build and publish Anaml Terraform provider

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  create:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANAML_ARTIFACT_PROJECT_ID: anaml-release-artifacts
      PUBLISH_BRANCH: refs/heads/master
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Configure Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.15.2"
      - name: Build Terraform providers
        run: |
          GOOS=darwin go build ./providers/terraform-provider-anaml
          GOOS=darwin go build ./providers/terraform-provider-anaml-operations
      - name: Install makeself
        if: startsWith(github.ref, 'refs/tags/release-')
        run: sudo apt-get install -y makeself
      - name: Package Terraform providers
        if: startsWith(github.ref, 'refs/tags/release-')
        run: ./package.sh
      - name: Publish Terraform providers
        if: startsWith(github.ref, 'refs/tags/release-')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: terraform-provider-anaml-install-*.run
